docs: Translate language to US

diff --git a/commit-msg b/commit-msg
--- a/commit-msg
+++ b/commit-msg
@@ -1,15 +1,15 @@
 #!/bin/sh
 
-# Regex para validar o padrão tipo 
+# Regex to validate the type pattern
 REGEX="^((Merge[ a-z-]* branch.*)|(Revert*)|((build|chore|ci|docs|feat|fix|perf|refactor|revert|style|test)(\(.*\))?!?: .*))"
 
-FILE=`cat $1` # Arquivo que contém a menssagem do commit
+FILE=`cat $1` # File containing the commit message
 
 echo "Commit Message: ${FILE}"
 
 if ! [[ $FILE =~ $REGEX ]]; then
-	echo >&2 "ERROR: Commit abortado por não seguir o padrão Conventional Commit.​"
+	echo >&2 "ERROR: Commit aborted for not following the Conventional Commit standard.​"
 	exit 1
 else
-	echo >&2 "​Mensagem de commit válida."
+	echo >&2 "Valid commit message."
 fi
